dist: "Xenial" 
language: python
python:
  - "3.8"

addons:
    snaps:
      - name: yq
        channel: v3/stable
      - jq

services:
  - docker

env:
  DOCKERHUB_USER:
    secure: ncyM5gbArjxGcczo/DKdv8xLyqRJx44fNYeOyUSJeVxoTCNGBcA79Jv9hPu3tHXdUGd2lHisjCEsSE6nZ0YmSZ2IipxtnDNu+HddZdNRPCL6HOE1EgreBJAK4+4TwOk6SOUnw+mF+fz796pIMpLq+xSciUQoxkVTXLaWT/orcoEnTgnEEWJkwWvPkDLnliC5OKnm6F1i8Rny+jKIO6gHBHanJeczspohURMzyXde9+PfAPsk8lFkSCVXDb+4kQlPaWod2djIyB1Ar6XewcxLA2fe/qyI/BTkBdTJu8sqFFUpc2dicQAAYx9prW3xdzCoaCtC/lVCmmrQlGqcpO7YJoCWPQClYdM1muDXMN0vVbmbUd95uapgKbQNqG8YDOq+7oRxCia7UFmhZAUPb2kK1Vt2yJYyEMOULVFKIapAb5DTUGONy8l8AQXnEWbq4XQCeUmbqJEnILJEAwPQTIwoVJXnIhJ6OP0uJi8oyQ1T3+oGKVWSUN0GzCCKlUeN5QL7UZIItpKkijfJ9WyP1bLMpvjCZBZjYF9RCTIiVXtg4reuVekSZ7PeTBBbK3Uwpl9GPvlTTq41QB1Tmb/qL0OmxL4x4CrXDTwIZCQ9BvKPg2Lr/QbIb7xyREZIlQcHjSuB/TJA/OsrJi538x+fBcdFtHU43Ed2wZ+ShF+nIfxYmMs=
  DOCKERHUB_TOKEN:
    secure: p7yQ6sWvT9Ui7ltNDmuEOmw6clJaWCL0QuPMLO5RUwpXllOIogoxAK/2sA6mcv4B+OdLfsHugrPfxPPSfCP2o41Tp1tKqwJniQCWu4KfMZtK47hEAg4f0fKVfv/TRRidfSjpeLpUFXEK+yk7ESz5rBNkwxGNeYCu02sFK/ZP5v1Qi1sXLvcXi7N6YRaJF1ST0LzSHjceDqnkgUkqf6aPctVA7/RKu1sfvG2TpH+T7i1i75C/rnKDst1QwL98H58HeDVIb+28HR7+1LatDDt2fV0z0ybNdmHXu+KN7rUZkEIPCwKJImYhQfltMl6CJb5uJejd9i+K8YrguRaEKje48bxUUSs+7SNnjV0Fe66FKM3ueelz2pxC35uQ1+TkOfXZf8NMcJcfAOPtkxJYXSbs0V+V2MUsmflJlyhnOppiP4VI+4JZAUkPNE4EXql/R5qA6paL/JTEkGw/j0ERF5ElsDe8Zs3BvYK6XJlWlQyOaeNwYKoFIgIi4/KbIA/DFoRg/dhow9kSfkKDw8olvuN0HaCqgmgsrRvIlcV68/QZHypYj3GzJv+q2hB5JMvUyCEcCv5yZyb3osiJqkHWUOJ0Bxd06N8V9J+pq5RF5Zl20bo/0CbILOE0qG884rWvchIq0PPcsNVDA9nU4sxZmtRXrr2krw2EjqdTAn6wEghyxFQ=

install:
  - pip3 install -r requirements.txt
  - pip3 install .

script: 
  - pytest
  - cd examples/basics
  - ./test/test_basics.sh
  - cd ../../

before_deploy:
  - echo TRAVIS_TAG=$TRAVIS_TAG
  - sed -i "s/TRAVISTAGHERE/${TRAVIS_TAG}/g" setup.py
  - cat setup.py

deploy:
  skip_cleanup: true
  provider: pypi
  username: __token__
  password:
    secure: GNXzs+nyElG3AtZ8p70RE9UqiQapUtlGl4qIXLs15BMyUNahknuRN/5XmpkMGsLpTUbY3AzzZP1RB4CbqWaw3YFQg2D7l2jToD14jHQsVM6VNnbGLpuD3YqsM/dqRSzm8nb5smYouvPRDdckh0NvKNX/kw5V8DI05plqWp4kkWg9MRPLTdQph7Y3nTrb20oqvcAO9dkI8Z5jjs2XACdxBgpYDFonxyTqlmDZiLoEo5l1+iwN6jfLICe8cmx9cjMOKzg7AKcmpPnttb7tWksRc5ULDKD+iiT6zCtbG56Hcf6xOM9HMB7mo66TYL3LvHqNs0yBgiTUqN9jShW/JX4GsASuHgoZYQsCC7N19E2GgXpOWMLHvF7JDc+Yhtj2UPNXJpgsKuJB/RWFyalXNv6y6ausdE8xJoIF4KwJpHjSRVne1X1XswCexS9iWINl8Y9YokJVwT9DTHZUT/ke9lJqruALaTfm0OcG25tWkaGB1NiSTiFZHhbcZA0tUp4/X/Ga7oO5xM3Z5HPxWygr77B8SuTRokLt0cKd9Kcmz8HIALrwOXtYdrZRPpWIxa2B1pkWjlj9GbeAhEOSDwp12dLr3hIuZuEUubm4VLVOdz0oa70HUdX3o58GKiWbAC4gXbpPesuyARXKv8QFqw79+Jk6Wm+aT4HhSAD0RljXnfseC1g=
  on:
    tags: true

# ugh, there is some latency in pypi, sleep....
after_deploy:
  - sleep 300
  - found=1; while [ $found -eq 1 ]; do sleep 5; x=$(curl -s https://pypi.org/simple/cicdstatemgr/ 2>&1 | grep $TRAVIS_TAG); found=$?; echo "found? $found";  done
  - docker build --build-arg GIT_TAG=$TRAVIS_TAG -t bitsofinfo/cicdstatemgr:$TRAVIS_TAG .
  - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker push bitsofinfo/cicdstatemgr:$TRAVIS_TAG
  - docker tag bitsofinfo/cicdstatemgr:$TRAVIS_TAG bitsofinfo/cicdstatemgr:latest
  - docker push bitsofinfo/cicdstatemgr:latest



