---

apiVersion: v1
kind: Pod
metadata:
  name: cicd-trivy-server
  labels:
    app: cicd-trivy-server
spec:
  containers:
    - image: docker.io/aquasec/trivy:0.19.2
      name: cicd-trivy-server
      command:
        - /bin/ash
      args:
        - -c
        - |
          /usr/local/bin/trivy \
          server --listen 0.0.0.0:8080

---

apiVersion: v1
kind: Service
metadata:
  name: cicd-trivy-server
spec:
  type: ClusterIP
  selector:
    app: cicd-trivy-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
